version: "3.8"
services:
  mutant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "4000:4000"
    depends_on:
      - mongo
    networks:
      - app-network
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
